name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/TCDSolar/SIDpy/_build/results?buildId=$(Build.BuildId)"
  CIBW_BUILD: cp36-* cp37-* cp38-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"

resources:
  repositories:
    - repository: OpenAstronomy
      type: github
      endpoint: TCDSolar
      name: OpenAstronomy/azure-pipelines-templates
      ref: master

trigger:
  branches:
    include:
      - '*'
    exclude:
      - '*backport*'
  tags:
    include:
      - 'v*'
    exclude:
      - '*dev*'
      - '*pre*'
      - '*post*'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    submodules: false
    coverage: codecov
    envs:
      - macos: py37
        name: py37_mac

      - windows: py37
        name: py37_win

      - linux: py37
        name: py37_lin

      - linux: codestyle
        name: codestyle


# On branches which aren't master, and not Pull Requests, build the wheels but only upload them on tags
- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.SourceBranch'], 'master'))) }}:
  - template: publish.yml@OpenAstronomy
    parameters:
      # Only Upload to PyPI on tags
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        pypi_connection_name : 'PyPI'

      test_extras: 'test'
      test_command: 'pytest -p no:warnings --doctest-rst -m "not figure" --pyargs sidpy'
      submodules: false
      targets:
#        - wheels_linux
#        - wheels_macos
        - sdist
      dependsOn:
        - py37_mac
        - py37_win
        - py37_lin
